-- Generated by scripts/generate-planning-seed.mjs
-- Source: src/data/planning.js + src/i18n/locales/{fr,nl}.json

BEGIN;

delete from public.planning_items where lang = 'fr';
delete from public.planning_items where lang = 'nl';

insert into public.planning_items (lang, phase_id, type, title, description, period, status, sort_order)
values
  ('fr', 'preparation', 'preparation', 'Achat des plants', 'Achat finalisé pour lancer la saison : 40,5 kg de plants (calibre 28/35) déjà récupérés (~1 570 plants).', '1–14 février 2026', 'done', 1),
  ('fr', 'preparation', 'preparation', 'Remboursement achat des plants', 'On boucle la répartition des coûts entre participants pour repartir clair.', '1–14 février 2026', 'todo', 2),
  ('fr', 'preparation', 'preparation', 'Tri + germination des plants (27 sacs)', 'On doit trier + lancer la germination proprement (40,5 kg / calibre 28/35).
⚡ J’aurais besoin d’un coup de main : ceux qui veulent venir aider sont les bienvenus 🙌', '1–14 février 2026', 'todo', 3),
  ('fr', 'preparation', 'preparation', 'Passage fermier (tracteur)', 'Passage mécanique pour ouvrir la parcelle avant préparation fine. Si pas fait: report au checkpoint suivant.', '15–28 février 2026', 'doing', 4),
  ('fr', 'preparation', 'preparation', 'Préparation terrain par la team (avant plantation)', 'Nettoyage, piquetage et repérage des rangs avant les sessions de plantation. Si pas fait: report au checkpoint suivant.', '1–14 mars 2026', 'todo', 5),
  ('fr', 'preparation', 'preparation', 'Checkpoint 1 — Organisation parcelle + matériel', 'On valide le plan des rangs, les zones de passage et le matériel d''arrosage. Si pas fait: report au checkpoint suivant.', '15–31 mars 2026', 'todo', 6),
  ('fr', 'plantation', 'plantation', 'Checkpoint 2 — Plantation session A', 'Première session collective de mise en terre avec espacement propre des rangs. Si pas fait: report au checkpoint suivant.', '1–14 avril 2026', 'todo', 7),
  ('fr', 'plantation', 'plantation', 'Checkpoint 3 — Plantation session B', 'Session de rattrapage pour les zones non plantées et ajustement des lignes. Si pas fait: report au checkpoint suivant.', '15–30 avril 2026', 'todo', 8),
  ('fr', 'plantation', 'plantation', 'Checkpoint 4 — Plantation session C', 'Session finale de plantation pour clôturer la mise en terre et homogénéiser la parcelle. Si pas fait: report au checkpoint suivant.', '1–14 mai 2026', 'todo', 9),
  ('fr', 'suivi', 'suivi', 'Checkpoint 5 — Buttage 1 + reprise des rangs', 'Premier buttage pour protéger les tubercules et consolider les lignes. Si pas fait: report au checkpoint suivant.', '15–31 mai 2026', 'todo', 10),
  ('fr', 'suivi', 'suivi', 'Checkpoint 6 — Arrosage ciblé + check feuillage', 'Arrosage uniquement si nécessaire et contrôle visuel global du feuillage. Si pas fait: report au checkpoint suivant.', '1–14 juin 2026', 'todo', 11),
  ('fr', 'suivi', 'suivi', 'Checkpoint 7 — Tour mildiou + buttage 2 si nécessaire', 'Tour sanitaire ciblé mildiou et deuxième buttage si des tubercules apparaissent en surface. Si pas fait: report au checkpoint suivant.', '15–30 juin 2026', 'todo', 12),
  ('fr', 'suivi', 'suivi', 'Checkpoint 8 — Suivi été: eau + feuillage', 'Point de routine pour garder le suivi sanitaire et l''arrosage alignés avant les premières récoltes. Si pas fait: report au checkpoint suivant.', '1–14 juillet 2026', 'todo', 13),
  ('fr', 'recolte', 'recolte', 'Checkpoint 9 — Test récolte des précoces', 'Test sur quelques pieds pour vérifier la maturité des précoces avant session élargie. Si pas fait: report au checkpoint suivant.', '15–31 juillet 2026', 'todo', 14),
  ('fr', 'recolte', 'recolte', 'Checkpoint 10 — Récolte précoces (session collective)', 'Session collective de récolte des précoces avec tri rapide sur place. Si pas fait: report au checkpoint suivant.', '1–14 août 2026', 'todo', 15),
  ('fr', 'recolte', 'recolte', 'Checkpoint 11 — Préparation récolte principale', 'On prépare les créneaux, zones de tri et cagettes pour lancer les récoltes tardives. Si pas fait: report au checkpoint suivant.', '15–31 août 2026', 'todo', 16),
  ('fr', 'recolte', 'recolte', 'Checkpoint 12 — Récolte principale vague 1', 'Première vague de récolte des variétés de conservation selon la maturité réelle. Si pas fait: report au checkpoint suivant.', '1–14 septembre 2026', 'todo', 17),
  ('fr', 'recolte', 'recolte', 'Checkpoint 13 — Récolte principale vague 2', 'Deuxième vague pour finir les zones restantes et limiter l''attente des tubercules en terre. Si pas fait: report au checkpoint suivant.', '15–30 septembre 2026', 'todo', 18),
  ('fr', 'conservation', 'conservation', 'Checkpoint 14 — Tri + mise en cagettes', 'Tri par état et usage puis mise en cagettes aérées pour entrer en stockage proprement. Si pas fait: report au checkpoint suivant.', '1–14 octobre 2026', 'todo', 19),
  ('fr', 'conservation', 'conservation', 'Checkpoint 15 — Point stockage (contrôle 1)', 'Contrôle des lots stockés et retrait des tubercules fragiles pour stabiliser le stockage. Si pas fait: report au checkpoint suivant.', '15–31 octobre 2026', 'todo', 20);

insert into public.planning_items (lang, phase_id, type, title, description, period, status, sort_order)
values
  ('nl', 'preparation', 'preparation', 'Aankoop van pootgoed', 'Aankoop afgerond om het seizoen te starten: 40,5 kg pootgoed (maat 28/35) al opgehaald (~1 570 stuks).', '1–14 februari 2026', 'done', 1),
  ('nl', 'preparation', 'preparation', 'Terugbetaling aankoop pootgoed', 'We ronden de kostenverdeling tussen deelnemers af zodat alles duidelijk blijft.', '1–14 februari 2026', 'todo', 2),
  ('nl', 'preparation', 'preparation', 'Sorteren + voorkiemen van pootgoed (27 zakken)', 'We moeten correct sorteren + voorkiemen opstarten (40,5 kg / maat 28/35).
⚡ Ik kan een extra hand gebruiken: wie wil helpen is meer dan welkom 🙌', '1–14 februari 2026', 'todo', 3),
  ('nl', 'preparation', 'preparation', 'Passage boer (tractor)', 'Mechanische voorbereiding om het perceel open te trekken voor de fijne afwerking. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '15–28 februari 2026', 'doing', 4),
  ('nl', 'preparation', 'preparation', 'Terreinvoorbereiding door het team (voor aanplanten)', 'Opruimen, uitzetten en rijen markeren voor de aanplantsessies. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '1–14 maart 2026', 'todo', 5),
  ('nl', 'preparation', 'preparation', 'Checkpoint 1 — Indeling perceel + materiaal', 'We bevestigen het rijenplan, de doorgangen en het materiaal voor watergeven. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '15–31 maart 2026', 'todo', 6),
  ('nl', 'plantation', 'plantation', 'Checkpoint 2 — Aanplantsessie A', 'Eerste gezamenlijke sessie om te planten met nette rij-afstanden. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '1–14 april 2026', 'todo', 7),
  ('nl', 'plantation', 'plantation', 'Checkpoint 3 — Aanplantsessie B', 'Inhaalsessie voor zones die nog niet geplant zijn en bijsturing van de lijnen. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '15–30 april 2026', 'todo', 8),
  ('nl', 'plantation', 'plantation', 'Checkpoint 4 — Aanplantsessie C', 'Laatste plantsessie om de aanplant af te ronden en het perceel homogeen te maken. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '1–14 mei 2026', 'todo', 9),
  ('nl', 'suivi', 'suivi', 'Checkpoint 5 — Aanaarden 1 + rijen bijwerken', 'Eerste aanaarding om knollen te beschermen en de rijen te versterken. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '15–31 mei 2026', 'todo', 10),
  ('nl', 'suivi', 'suivi', 'Checkpoint 6 — Gericht watergeven + loofcheck', 'Alleen water geven indien nodig en een algemene visuele controle van het loof. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '1–14 juni 2026', 'todo', 11),
  ('nl', 'suivi', 'suivi', 'Checkpoint 7 — Rondgang meeldauw + aanaarden 2 indien nodig', 'Gerichte gezondheidscontrole en tweede aanaarding als knollen bovenkomen. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '15–30 juni 2026', 'todo', 12),
  ('nl', 'suivi', 'suivi', 'Checkpoint 8 — Zomeropvolging: water + loof', 'Routinepunt om gezondheidsopvolging en watergift op koers te houden voor de eerste oogst. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '1–14 juli 2026', 'todo', 13),
  ('nl', 'recolte', 'recolte', 'Checkpoint 9 — Oogsttest vroege rassen', 'Test op enkele planten om rijpheid te checken vóór een bredere sessie. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '15–31 juli 2026', 'todo', 14),
  ('nl', 'recolte', 'recolte', 'Checkpoint 10 — Oogst vroege rassen (teamsessie)', 'Gezamenlijke oogstsessie voor de vroege rassen met snelle triage op het veld. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '1–14 augustus 2026', 'todo', 15),
  ('nl', 'recolte', 'recolte', 'Checkpoint 11 — Voorbereiding hoofdoogst', 'We plannen tijdsloten, triagezones en kistjes om de latere oogst op te starten. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '15–31 augustus 2026', 'todo', 16),
  ('nl', 'recolte', 'recolte', 'Checkpoint 12 — Hoofdoogst golf 1', 'Eerste golf van de oogst van bewaarrassen volgens de echte rijpheid. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '1–14 september 2026', 'todo', 17),
  ('nl', 'recolte', 'recolte', 'Checkpoint 13 — Hoofdoogst golf 2', 'Tweede golf om resterende zones af te werken en knollen niet te lang in de grond te laten. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '15–30 september 2026', 'todo', 18),
  ('nl', 'conservation', 'conservation', 'Checkpoint 14 — Sorteren + in kistjes', 'Sorteren op staat en gebruik, daarna in geventileerde kistjes voor nette opslag. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '1–14 oktober 2026', 'todo', 19),
  ('nl', 'conservation', 'conservation', 'Checkpoint 15 — Opslagpunt (controle 1)', 'Controle van de opgeslagen partijen en verwijderen van kwetsbare knollen om de opslag stabiel te houden. Als het niet lukt: doorschuiven naar de volgende checkpoint.', '15–31 oktober 2026', 'todo', 20);

COMMIT;
